const text = {
    HOME_TEXT: "Home",
    ABOUT_TEXT: "About",
    RESUME_TEXT: "Resume",
    WORKS_TEXT: "Works",
    SOCIAL_TEXT: "Social",
    CONTACT_TEXT: "Contact",
    NAME_TEXT: "Alex Ichenskyi",
    NAME_SUB_TEXT_FIRST: "Full Stack developer",
    NAME_SUB_TEXT_SECOND: "tiny workshop",
    GITHUB_TEXT: "GitHub",
    ABOUT_ME_TEXT: "About Me",
    ABOUT_ME_SUB_TEXT: `Hey! I'm Alex, web developer based in Zagreb. My biggest passion is code, \
                           content and design that builds an exceptional digital experience. Currently, I'm \
                           studying at FER and focused on creating human-centered and incredible \
                           highly scalable software systems of any complexity.`,
    DOWNLOAD_RESUME_TEXT: "Download Resume",
    EDUCATION_TEXT: "I am honored to study at",
    UNIVERSITY_NAME_TEXT: "FER",
    UNIVERSITY_DATE_MSC_TEXT: <span><i>Master of Science in Computer Science</i> • 2024 - 2026</span>,
    UNIVERSITY_DATE_TEXT: <span><i>Bachelor of Science in Computing</i> • 2021 - 2024</span>,
    SCHOOL_NAME_TEXT: "V. Gymnasium",
    SCHOOL_DATE_TEXT: <span><i>Secondary education</i> • 2017 - 2021</span>,
    PASSION_TEXT: "I'm always curious about...",
    HTML_TEXT: "HTML",
    CSS_TEXT: "CSS",
    JS_TEXT: "JAVASCRIPT",
    REACT_TEXT: "REACT",
    JAVA_TEXT: "JAVA",
    SPRING_TEXT: "SPRING",
    SQL_TEXT: "SQL",
    LINUX_TEXT: "LINUX",
    DOCKER_TEXT: "DOCKER",
    GIT_TEXT: "GIT",
    SCIENCE_TEXT: "COMPUTER SCIENCE",
    REST_TEXT: "REST API",
    FRONTEND_TEXT: "FRONTEND",
    BACKEND_TEXT: "BACKEND",
    MEMGRAPH_TEXT: "MEMGRAPH",
    GRAPH_DATABASE_TEXT: "GRAPH DATABASES",
    STARTUPS_TEXT: "STARTUPS",
    ART_TEXT: "ART",
    DESIGN_BY_TEXT: <>Made with <span className="heart">❤</span> by </>,
    ME_TEXT: "me",
    WORKING_ON_TEXT: "I`m currently working on...",
    ODIN_TEXT: "ODIN",
    RUNE_TEXT: "RUNE",
    PEEPO_TEXT: "Peepo Eats API",
    GIT_CALENDAR_TEXT: "Git Calendar",
    ALLIEN_TEXT: "Allien",
    POLICHROMA_TEXT: "Polichroma",
    WIDGETS_TEXT: "...and some widgets...",
    WEATHER_WIDGET_TEXT: "Weather Widget",
    CARD_WIDGET_TEXT: "Credit Card Widget"
}

export default text;